// Therapist-Portfolio\src\app\layout.js

import { Noto_Sans } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

import Navbar from "./components/Navbar";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
